; F103 — BMS虚拟节点 (CAN 500k → F407)
[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -I include
upload_protocol = stlink
